TaskGuider/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_guider.urls'))
]

task_guider/urls.py
from django.urls import path
from . import views
from .views import event_data


app_name = "task_guider"
urlpatterns = [
    path("", views.login_page, name="login_page"),
    path("accounts/login/", views.login_page),
    path("dashboard", views.dashboard, name="dashboard"),
    path("events", views.events, name="events"),
    path("event_data", event_data, name="event_data"),
    path("overview", views.overview, name="overview"),
    path("project_view/<int:id>/", views.project_view, name="project_view"),
    path("projects", views.projects, name="projects"),
    path("register", views.register_user, name="register"),
    path("settings", views.settings, name="settings"),
    path("task/<int:id>/", views.task, name="task"),
    path("download/<int:task_id>/<int:file_id>/", views.download_file, name="download"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("delete_task_type/<int:id>/", views.delete_task_type, name="delete_task_type"),
]

task_guider/models.py
from django.db import models
from django.contrib.auth.models import User


HIDE = (
    ("Visible", "Show on Dashboard"),
    ("Hidden",  "Hide from Dashboard")
)
COLORS = (
    ("#FF0000", "Red"),
    ("#FF7F00", "Orange"),
    ("#FFFF00", "Yellow"),
    ("#00FF00", "Green"),
    ("#00FFFF", "Cyan"),
    ("#0000FF", "Blue"),
    ("#7F00FF", "Violet"),
    ("#FF00FF", "Magenta"),
)
ICONS = (
    ('<i class="bi bi-tools"></i>', 'Repair'),
    ('<i class="bi bi-hammer"></i>', 'New Install'),
    ('<i class="bi bi-bug-fill"></i>', 'Bug'),
    ('<i class="bi bi-stars"></i>', 'Feature'),
    ('<i class="bi bi-ethernet"></i>', 'Network'),
)


class Project(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(choices=COLORS)

    def __str__(self):
        return self.name


class WorkState(models.Model):
    name = models.CharField(max_length=100)
    position = models.IntegerField()
    is_hidden = models.CharField(choices=HIDE)

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=25)
    icon = models.CharField(choices=ICONS)

    def __str__(self):
        return self.name


class Comment(models.Model):
    body = models.CharField(max_length=500)
    date_created = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    parent_post = models.ForeignKey('TaskPost', on_delete=models.PROTECT)


class TaskPost(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    work_state = models.ForeignKey(WorkState, on_delete=models.PROTECT, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)
    due_date = models.DateField()
    body = models.TextField(max_length=1000)
    show_on_calendar = models.BooleanField(null=True, blank=True)
    type = models.ForeignKey(TaskType, on_delete=models.PROTECT, null=True, blank=True)
    project_name = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    comments = models.ForeignKey(Comment,on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.title

task_guider/forms.py
from django import forms
from django.forms import ModelForm
from .models import WorkState, TaskType, Project, Comment, TaskPost
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class CreateTaskForm(forms.Form):
    title = forms.CharField(label="Title", required=True, max_length=100)
    subtitle = forms.CharField(label="Subtitle", required=True, max_length=100)
    work_state = forms.ModelChoiceField(label="Select Work State",
                                        queryset=WorkState.objects.all(), to_field_name='name', required=True)
    body = forms.CharField(label="Content", widget=forms.Textarea(attrs={'name': 'body', 'rows': '3', 'cols': '5'}))
    due_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    show_on_calendar = forms.BooleanField(label="Show on Calendar?")
    type = forms.ModelChoiceField(label="Select Task Type if applicable",
                                  queryset=TaskType.objects.all(), to_field_name='name', required=True)
    project = forms.ModelChoiceField(label="Select Project",
                                     queryset=Project.objects.all(), to_field_name='name', required=True)


class EditTaskForm(ModelForm):
    class Meta:
        model = TaskPost
        fields = ["title", "subtitle", "work_state", "body", "due_date", "show_on_calendar", "type", "project_name"]


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}), required=True)
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), required=True)


class RegistrationForm(forms.Form):
    email = forms.EmailField(label="Email Address", required=True)
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}), required=True)
    name = forms.CharField(max_length=100, required=True)
    is_admin = forms.BooleanField(label="Set Admin")


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]
        labels = {
            "body": _("Comments"),
        }


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "color"]


class WorkStateCreateForm(ModelForm):
    class Meta:
        model = WorkState
        fields = ["name", "position", "is_hidden"]
        labels = {
            "is_hidden": _("Visibility"),
        }


class WorkStateEditForm(ModelForm):
    class Meta:
        model = WorkState
        fields = ["position", "is_hidden"]
        labels = {
            "is_hidden": _("Visibility"),
        }


class WorkStateChangeFrom(forms.Form):
    new_work_state = forms.ModelChoiceField(label="Select Work State",
                                        queryset=WorkState.objects.all(), to_field_name='name', required=True)


class TaskTypeForm(ModelForm):
    class Meta:
        model = TaskType
        fields = ["name", "icon"]
        labels = {
            "name": _("Task Type Name"),
        }


class RegisterNewUserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "is_staff", "password"]
        labels = {

        }

task_guider/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from django.db.models import F, Q, Count
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Project, TaskPost, WorkState, TaskType, Comment
from .forms import (CreateTaskForm, WorkStateCreateForm, EditTaskForm, WorkStateChangeFrom, CommentForm, ProjectForm,
                    LoginForm, RegisterNewUserForm, TaskTypeForm, WorkStateEditForm)
from django.contrib.auth.models import User
from subscribed.models import Subscribed
import json
import plotly
import plotly.express as px
from django.db import connection
import pandas as pd
from datetime import datetime


def login_page(request):
    context = {"login_form": LoginForm()}
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if "login_request" in request.POST:
            if not login_form.is_valid():
                print(login_form.errors)
                HttpResponseRedirect("#")
            elif login_form.is_valid():
                username = login_form.cleaned_data["username"]
                password = login_form.cleaned_data["password"]
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('task_guider:dashboard')
                else:
                    print("user is none or incorrect creds")
                    HttpResponseRedirect("#")
    else:
        login_form = LoginForm()
        return render(request, "login.html", context)


@login_required
def dashboard(request):
    context = {'task_form': CreateTaskForm(), "work_state_create_form": WorkStateCreateForm(),
               'work_states': list(WorkState.objects.all()), 'tasks': list(TaskPost.objects.all())}
    if request.method == "POST":
        task_form = CreateTaskForm(request.POST)
        work_state_create_form = WorkStateCreateForm(request.POST)
        if "task_form" in request.POST:
            if not task_form.is_valid():
                print(task_form.errors)
                return HttpResponseRedirect("#")
            elif task_form.is_valid():
                new_task = TaskPost()
                new_task.title = task_form.cleaned_data["title"]
                new_task.subtitle = task_form.cleaned_data["subtitle"]
                new_task.work_state = task_form.cleaned_data["work_state"]
                new_task.body = task_form.cleaned_data["body"]
                new_task.due_date = task_form.cleaned_data["due_date"]
                new_task.show_on_calendar = task_form.cleaned_data["show_on_calendar"]
                new_task.type = task_form.cleaned_data["type"]
                new_task.project_name = task_form.cleaned_data["project"]
                new_task.author = request.user
                new_task.save()
                return HttpResponseRedirect("#")
        if "work_state_form" in request.POST:
            if not work_state_create_form.is_valid():
                print(work_state_create_form.errors)
                return HttpResponseRedirect("#")
            elif work_state_create_form.is_valid():
                new_work_state = WorkState()
                new_work_state.name = work_state_create_form.cleaned_data["name"]
                new_work_state.position = work_state_create_form.cleaned_data["position"]
                new_work_state.is_hidden = work_state_create_form.cleaned_data["is_hidden"]
                new_work_state.save()
                return HttpResponseRedirect("#")
    else:
        task_form = CreateTaskForm()
        work_state_create_form = WorkStateCreateForm()
        return render(request, "dashboard.html", context)


@login_required
def events(request):
    context = {}
    return render(request, "events.html", context)


@login_required
def event_data(request):
    data = []
    start_date = request.GET.get('start').replace("-", "")[:8]
    end_date = request.GET.get('end').replace("-", "")[:8]
    calendar_events = TaskPost.objects.filter(show_on_calendar=True).order_by('due_date')
    for calendar in calendar_events:
        if int(start_date) <= int(calendar.due_date.strftime('%Y%m%d')) <= int(end_date):
            event = {
                "title": f"{calendar.title}",
                "start": f"{calendar.due_date}",
                "url": reverse('task_guider:task', kwargs={'id': calendar.id})
            }
            data.append(event)
    return JsonResponse(data, safe=False)


@login_required
def overview(request):
    bar_chart = bar_chart_task()
    context = {'bar_chart': bar_chart}
    return render(request, 'overview.html', context)


def bar_chart_task():
    task_counts = TaskPost.objects.values('work_state').annotate(count=Count('work_state')).order_by('work_state')
    work_states = WorkState.objects.filter(is_hidden='not_hidden').values('name', 'id', 'position').order_by('position')

    df_task_count = pd.DataFrame(task_counts)
    df_work_state = pd.DataFrame(work_states)

    df_work_state.index += 1
    df_graph = df_work_state.set_index('position').join(df_task_count.set_index('work_state'))
    df_graph = df_graph.fillna(0)

    max_count = df_graph['count'].max()

    fig = px.bar(df_graph, x='name', y='count', labels={'x': 'Work State', 'count': "# of Tasks"},
                 barmode="group")
    fig.update_layout(yaxis_range=[0, max_count + (2 * max_count)], xaxis_title='')
    fig.update_traces(marker_color='green')

    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return graphJSON


@login_required
def project_view(request, id):
    project = get_object_or_404(Project, id=id)
    context = {"project": project, "work_states": list(WorkState.objects.all()), "tasks": list(TaskPost.objects.filter(project_name=project.id).order_by('work_state'))}
    return render(request, "project_view.html", context)


@login_required
def projects(request):
    context = {"projects": list(Project.objects.all()), "project_form": ProjectForm()}
    if request.method == "POST":
        project_form = ProjectForm(request.POST)
        if "project_form" in request.POST:
            if not project_form.is_valid():
                print(project_form.errors)
                return HttpResponseRedirect('#')
            elif project_form.is_valid():
                project_form.save()
                return HttpResponseRedirect('#')
    else:
        project_form = ProjectForm()
        return render(request, "projects.html", context)


@login_required
def register_user(request):
    pass


@login_required
def settings(request):
    context = {"register_new_user_form": RegisterNewUserForm(), "work_state_create_form": WorkStateCreateForm(),
               "work_state_edit_form": WorkStateEditForm(), "new_task_type": TaskTypeForm(),
               "work_states": WorkState.objects.all().order_by('position'), "users": list(User.objects.all()),
               "task_types": list(TaskType.objects.all()),}
    if request.method == "POST":
        register_new_user_form = RegisterNewUserForm(request.POST)
        work_state_create_form = WorkStateCreateForm(request.POST)
        work_state_edit_form = WorkStateEditForm(request.POST)
        new_task_type = TaskTypeForm(request.POST)
        if "register_new_user_form" in request.POST:
            if not register_new_user_form.is_valid():
                return HttpResponseRedirect('#')
            if register_new_user_form.is_valid():
                return HttpResponseRedirect('#')
        if "work_state_create_form" in request.POST:
            if not work_state_create_form.is_valid():
                return HttpResponseRedirect('#')
            if work_state_create_form.is_valid():
                return HttpResponseRedirect('#')
        if "work_state_edit_form" in request.POST:
            if not work_state_edit_form.is_valid():
                print(work_state_edit_form.errors)
                return HttpResponseRedirect('#')
            if work_state_edit_form.is_valid():
                work_state_id = request.POST.get('work_state_id')
                work_state_edit = get_object_or_404(WorkState, id=work_state_id)
                work_state_edit.position = work_state_edit_form.cleaned_data["position"]
                work_state_edit.is_hidden = work_state_edit_form.cleaned_data["is_hidden"]
                work_state_edit.save()
                return HttpResponseRedirect('#')
        if "new_task_type_form" in request.POST:
            if not new_task_type.is_valid():
                print(new_task_type.errors)
                return HttpResponseRedirect('#')
            if new_task_type.is_valid():
                new_task_type.save()
                return HttpResponseRedirect('#')
        if "user_deactivate" in request.POST:
            if request.user.is_authenticated and request.user.is_staff:
                user_id = request.POST.get("user_id")
                user = get_object_or_404(User, id=user_id)
                user.is_active = False
                user.save()
                return HttpResponseRedirect('#')
        if "user_activate" in request.POST:
            if request.user.is_authenticated and request.user.is_staff:
                user_id = request.POST.get("user_id")
                user = get_object_or_404(User, id=user_id)
                user.is_active = True
                user.save()
                return HttpResponseRedirect('#')
    else:
        register_new_user_form = RegisterNewUserForm()
        work_state_create_form = WorkStateCreateForm()
        work_state_edit_form = WorkStateEditForm()
        new_task_type = TaskTypeForm()
        return render(request, "settings.html", context)


@login_required

task_guider/templates/401.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Robert Worsham" />
        <title> Error 401 </title>
        <link rel="icon" href="{% static 'assets/favicon.svg' %}" type="image/svg+xml">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'task_guider:login %}" >Task Guider<i class="bi bi-cloud-haze2"></i></a>
            </div>
        </nav>
       <h1 class="display-5 fw-bold text-body-emphasis text-center">Error 401</h1>
       <h5 class="text-center">You could not be authenticated please <a href="{% url 'task_guider:login %}">Login</a>, verify you have been registered or contact support.</h5>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

task_guider/templates/events.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Robert Worsham" />
        <title>Task Guider</title>
        <link rel="icon" href="{% static 'assets/favicon.svg' %}" type="image/svg+xml">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet'>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.12/index.global.min.js"></script>
        <script>

          document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
              initialView: 'dayGridMonth',
              eventColor: '#20c997',
              height: '90%',
              eventSources: [

                // your event source
                {
                  url: '/event_data', // use the `url` property
                  color: '#20c997',    // an option!
                  textColor: 'black',  // an option!
                  format: 'json'
                }

                // any other sources...

              ],
              views: {
                dayGridMonth: {
                    dayMaxEventRows: 3 // Limit the number of event rows per day
                }
              }
            });
            calendar.render();
          });
        </script>
    <body>
    {% load crispy_forms_tags %}
        <div class="d-flex" id="wrapper">
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Task Guider<i class="bi bi-cloud-haze2"></i></div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:overview' %}">Overview</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:dashboard' %}">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:projects' %}">Projects</a>
                    <a class="list-group-item list-group-item-action list-group-item-dark p-3" href="{% url 'task_guider:events' %}">Calendar</a>
                </div>
            </div>
            <div id="page-content-wrapper">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-secondary" id="sidebarToggle"><i class="bi bi-chevron-double-left"></i></button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item"><a class="nav-link" >{{ request.user.username }}</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-gear-wide"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="{% url 'task_guider:settings' %}">Settings</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'task_guider:logout_user' %}">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="container-fluid" id="calendar"></div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

task_guider/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Robert Worsham" />
        <title> Log In </title>
        <link rel="icon" href="{% static 'assets/favicon.svg' %}" type="image/svg+xml">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
       {% load crispy_forms_tags %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" >Task Guider<i class="bi bi-cloud-haze2"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                </div>
            </div>
        </nav>
        <main class="mb-4">
          <div class="container center">
            <div class="row">
              <div class="col-lg-8 col-md-10 mx-auto">
                  <form method="POST">
                      {% csrf_token %}
                      {{ login_form|crispy }}
                      <button class="btn btn-success" type="submit" name="login_request">Login</button>
                  </form>
              </div>
            </div>
          </div>
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

task_guider/templates/projects.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Robert Worsham" />
        <title>Task Guider</title>
        <link rel="icon" href="{% static 'assets/favicon.svg' %}" type="image/svg+xml">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% load crispy_forms_tags %}
        <div class="d-flex" id="wrapper">
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Task Guider<i class="bi bi-cloud-haze2"></i></div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:overview' %}">Overview</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:dashboard' %}">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-dark p-3" href="{% url 'task_guider:projects' %}">Projects</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'task_guider:events' %}">Calendar</a>
                </div>
            </div>
            <div id="page-content-wrapper">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid gap-2">
                        <button class="btn btn-secondary" id="sidebarToggle"><i class="bi bi-chevron-double-left"></i></button>
                        <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#add-project"><i class="bi bi-patch-plus"></i> Add Project</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item"><a class="nav-link" >{{ request.user.username }}</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-gear-wide"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="{% url 'task_guider:settings' %}">Settings</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'task_guider:logout_user' %}">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="modal fade" id="add-project" tabindex="-1" aria-labelledby="add-project-label" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="add-todo-label">New Project</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="row">
                            <form class="row g-3" method=post>
                               {% csrf_token %}
                                {{ project_form|crispy }}
                                <button class="btn btn-success" type="submit" name="project_form">Save</button>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="container-fluid dashboard-scroll">
                   <div class="row">
                       {% for project in projects %}
                        <div class="col-lg-2 mt-3">
                            <div class="card h-100">
                                <div class="card-header" style="background-color: {{project.color}};"></div>
                                    <div class="card-body bg-light">
                                        <h5 class="card-title">{{ project.name }}</h5>
                                        <a href="{% url 'task_guider:project_view' project.id %}" class="stretched-link"></a>
                                    </div>
                            </div>
                        </div>
                       {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% if project_form_error %}
        <script type="text/javascript">
            window.onload = () => {
              const myModal = new bootstrap.Modal('#add-project');
              myModal.show();
            }
        </script>
        {% endif %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>